[versions]
agp = "8.5.1"
kotlin = "2.0.0"
htmlcleaner = "2.29"
cssparser = "1.7"
dokka = "1.9.20"
android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "34"
jvmTarget = "17"

[libraries]
htmlcleaner = { module = "net.sourceforge.htmlcleaner:htmlcleaner", version.ref = "htmlcleaner" }
cssparser = { module = "com.osbcp:cssparser", version.ref = "cssparser" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
# 下面这个是假的，只是为了占位
jvmTargetPlaceHolder = { id = "org.jdk.kotlin.holder", version.ref = "jvmTarget" }
